---
- name: "nodejs {{ nodejs.version }} をインストール"
  shell: $SHELL -lc "nvm install {{ nodejs.version }}"
  become: yes

- name: "nodejsのデフォルトバージョンを設定"
  shell: $SHELL -lc "nvm alias default node"
  become: yes
