---
- name: install dependencies via YUM
  yum: name={{ item }} state=present
  with_items:
    - git
    - gcc
    - gcc-c++
    - make
    - openssl-devel
    - libselinux-python
  sudo: true

- name: checkout nvm repo from {{ nvm.root }}
  git: repo={{ nvm.repo }}
       dest={{ nvm.root }}
       accept_hostkey=yes
       force=yes
  sudo: true

- name: add nvm initialization to profile system-wide
  template: > 
    src=etc/profile.d/nvm.sh.j2
    dest=/etc/profile.d/nvm.sh
    owner=root 
    group=root 
    mode=0755
  sudo: true

- name: upgrade nvm
  shell: $SHELL -lc "git pull origin master && git checkout `git describe --abbrev=0 --tags`"
  args:
    chdir: "{{ nvm.root }}"
  sudo: true

- shell: $SHELL -lc ". {{ nvm.root }}/nvm.sh"
  sudo: true

- name: check if {{ nvm.group }} group is exists
  group: name={{ nvm.group }} state=present gid={{ nvm.gid }}
  sudo: true

- name: change ownership, group and mode of nvm
  file: path={{ nvm.root }}
        owner=root
        group={{ nvm.group }}
        mode="u=rwx,g=rwx,o=rx"
        recurse=yes
  sudo: true
